name: cico_site
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.codeindiacompany.com
# author: Mridul <mridulsahu01@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.1.4
  angular_router: ^2.0.0-alpha+24

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.0
  built_html: ^0.1.3
